name: Auto Update README

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Run update script
        working-directory: ${{ github.workspace }}
        run: |
          echo "Current directory: $(pwd)"
          ls -R  # just to debug your repo structure
          python3 update_readme.py

      - name: Commit and push changes
        working-directory: ${{ github.workspace }}
        run: |
          git config --global user.name "akashkhairnar"
          git config --global user.email "akashkhairnar40@gmail.com"
          git add README.md
          git diff --staged --quiet || git commit -m "Auto-update README"
          git push
