
name: Auto Update README

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 👈 important! full git history

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Run update script
        working-directory: ${{ github.workspace }}
        run: |
          echo "Current directory: $(pwd)"
          python3 update_readme.py
          cat README.md | head -n 20  # show first 20 lines to verify

      - name: Commit and push changes
        working-directory: ${{ github.workspace }}
        run: |
          git config --global user.name "akashkhairnar"
          git config --global user.email "akashkhairnar40@gmail.com"
          git add README.md
          if ! git diff --staged --quiet; then
            git commit -m "Auto-update README with LeetCode links"
            git push origin HEAD:${{ github.ref_name }}
          else
            echo "No changes to commit"
          fi
